import Head from "next/head";
import Image from "next/image";
import Item_List from "../components/Forms/Item_List";
import NewItem from "../components/NewItem";
import { Main } from "../styles";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { BASE_API_URL } from "./api/constants";

export default function Home({ itemList, categoryList, storeList, data }) {
  console.log(itemList);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        {/* <NewItem itemList={itemList} /> */}

        <Item_List
          itemList={itemList}
          categoryList={categoryList}
          storeList={storeList}
        />
      </>
    </div>
  );
}

export const getStaticProps = async ({ req, res }) => {
  const response = await axios.get(`${BASE_API_URL}/catalog/items`);
  const itemList = await response.data;

  const resp = await axios.get(`${BASE_API_URL}/catalog/categories`);
  const categoryList = await resp.data;

  const respond = await axios.get(`${BASE_API_URL}/catalog/stores`);
  const storeList = await respond.data;

  return {
    props: {
      itemList,
      categoryList,
      storeList,
      // data: data && data,
    },
  };
};
