import Head from "next/head";
import Image from "next/image";
import Item_List from "../components/Forms/Item_List";

import NewItem from "../components/NewItem";
import { Main } from "../styles";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { BASE_API_URL } from "./api/constants";

export default function Home({ itemList }) {
  console.log(itemList);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        {/* <NewItem itemList={itemList} /> */}

        <Item_List itemList={itemList} />
      </>
    </div>
  );
}

export const getStaticProps = async (context) => {
  const res = await axios.get(`${BASE_API_URL}/catalog/items`);
  const itemList = await res.data;

  return {
    props: {
      itemList,
    },
  };
};
