version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    networks:
      - rated-app
    volumes:
      - ./server/nginx/default.conf:/etc/nginx/conf.d

  rated-app-server:
    # restart: always
    build:
      context: ./server
    environment:
      - PORT=5000
    networks:
      - rated-app
    depends_on:
      - mongo

  next-app:
    # restart: always
    build:
      context: ./rated-app
    ports:
      - "3005:3005"
    # volumes:
    #   - ./:/app
    #   - ./pages:/app/pages
    #   - /app/node_modules
    #   - /app/.next
    networks:
      - rated-app

  mongo:
    # build:
    #   context: ./server
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - rated-app
    volumes:
      - mongo-db:/data/db

  redis:
    # build:
    #   context: ./server
    image: redis
    networks:
      - rated-app

networks:
  rated-app:
    driver: bridge
volumes:
  mongo-db:
