version: "3.9"

services:
  nginx:
    restart: always
    depends_on:
      - rated-app-server
      - client
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 8000:80
    networks:
      - rated-app

  client:
    restart: always
    build:
      context: ./rated-app
      dockerfile: Dockerfile.dev
    container_name: rated_app_frontend
    volumes:
      - ./rated-app:/app
      - /app/node_modules
    depends_on:
      - rated-app-server
    networks:
      - rated-app

  rated-app-server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: rated_app_nginx
    volumes:
      - ./server/:/app
      - /app/node_modules
    # ports:
    #   - 5000:5000
    depends_on:
      - mongo
      - redis
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      SESSION_SECRET: ${SESSION_SECRET}

    networks:
      - rated-app

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-db:/data/db
    networks:
      - rated-app

  redis:
    image: redis
    networks:
      - rated-app

volumes:
  mongo-db:
networks:
  rated-app:
    driver: bridge
