version: "3"
services:
  nginx:
    ports:
      - "8000:80"

  rated-app-server:
    build:
      context: ./server
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - MONGO_USER=rated-app
      - MONGO_PASSWORD=Youngboss89
      - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rated-app
      - MONGO_INITDB_ROOT_PASSWORD=Youngboss89
