version: "3"
services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
      - "3005:3005"
    volumes:
      - ./:/app
      - ./pages:/app/pages
      - /app/node_modules
      - /app/.next
    environment:
      - CHOIDAR_USEPOLLING=true
