version: "3"
services:
  next-app:
    build:
      context: .
    stdin_open: true
    ports:
      - "3005:3005"
    networks:
      - rated-app

networks:
  rated-app:
    driver: bridge
