
@baseUrl = http://localhost:80/api/v1

POST  {{baseUrl}}/users/signup
Content-Type: application/json


{
    "username": "bizzhle",
    "password": "youngboss"
}

# {
#     "username": "Emilia",
#     "password": "emilia1810"
# }

# {
#     "name": "Books"
# }



