version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  rated-app-server:
    build: .
    environment:
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rated-app
      - MONGO_INITDB_ROOT_PASSWORD=Youngboss89
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
