version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    networks:
      - rated-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  rated-app-server:
    build: .
    environment:
      - PORT=5000
    networks:
      - rated-app
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rated-app
      - MONGO_INITDB_ROOT_PASSWORD=Youngboss89
    networks:
      - rated-app
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    networks:
      - rated-app

networks:
  rated-app:
    driver: bridge
volumes:
  mongo-db:
