version: "3"
services:
  rated-app-server:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    # environment:
    #     - PORT=3000
    # env_file:
    #     - ./.env
